Baegae/esruoc

- client/.eslintrc
- client/@types/editorjs.d.ts
- client/package.json
- client/pages/editor-js-test.tsx
- client/src/components/EditorJSTest/QuizBlock/index.tsx
- client/src/components/EditorJSTest/QuizBlock/plugin.tsx
- client/src/components/EditorJSTest/index.tsx
- client/tsconfig.json
- yarn.lock
> feat(client): EditorJS를 React와 연동

- .dockerignore
- Dockerfile
- docker-compose-local.yaml
- run_dev.sh
- 도오커 파일을 추가합니다.
- closes: #10 
- 현재 docker run에 문제가 있어요...
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/lectus/run_dev.sh\": permission denied": unknown.
```
- 로그파일도 `tee`로 만들자!
> feat(server): Dockerfile 추가

- server/package.json
- shared/src/entity/InProgressLecture.ts
- shared/src/entity/Lecture.ts
- shared/src/entity/Lesson.ts
- shared/src/entity/User.ts
- yarn.lock
- 유저 엔티티를 추가했어요!
- 강의 엔티티를 추가했어요!
> feat: 유저 / 강의 엔티티 추가

- client/@types/recordrtc.d.ts
- client/package.json
- client/pages/add-video.tsx
- client/src/components/VideoTest/index.tsx
- yarn.lock
- 변경 사항을 입력하세요.
- **없다면 해당 섹션을 지우세요**
- 추가 사항을 입력하세요. (없으면 지우세요!)
> feat(client): VideoTest 컴포넌트를 만듬

- shared/.eslintrc
- shared/package.json
- shared/src/entity/InProgressLecture.ts
- shared/src/entity/Lecture.ts
- shared/src/entity/Lesson.ts
- shared/src/entity/User.ts
- Shared 모듈에 린트 적용, 수정사항을 반영했어요!
> fix(shared): 린트 적용 / 수정사항 반영

- .gitignore
- docker-compose-local.yaml
- server/nodemon.json
- server/package.json
- server/src/index.ts
- server/tsconfig.json
- yarn.lock
- Hot Reload 기능을 추가했어요!
- Firebase 를 사용하기 위해서 `firebase-admin-sdk` 라이브러리를 추가했고, 초기화 하는 코드를 추가했어용
> feat(backend): Hot Reload / Firebase 앱 초기화 기능 추가

- server/src/database/Firebase.ts
> feat: Firebase 클래스가.. 커밋이 안됐넹........................................ ㅈㅅ

- docker-compose-local.yaml
- server/package.json
- docker-compose의 image 이름을 esruoc으로 변경합니다.
- Server package.json의 project 이름도 변경합니다.
> fix(server): docker-compose의 image 이름 변경

- docker-compose-local.yaml
- server/package.json
- server/src/business/LectureService.ts
- server/src/controller/LectureController.ts
- server/src/controller/SuccessResponse.ts
- server/src/database/Firebase.ts
- server/src/database/schema/LectureSchema.ts
- server/src/index.ts
- server/src/repository/LectureRepository.ts
- server/swagger.config.ts
- server/test/LectureAPIScratch.http
- shared/src/entity/Lecture.ts
- shared/src/request/CreateLectureRequest.ts
- shared/src/response/CreateLectureResponse.ts
- shared/src/response/SuccessResponse.ts
- yarn.lock
- 강의 추가 API 를 추가했어요!
- Swagger 로 백엔드 문서를 추가했어요!
- Firebase 에 파일 업로드 / 다운로드를 할 수 있는 매니징 클래스를 작성했어요!
> feat(backend): 강의 추가 API 추가

- client/package.json
- client/src/components/Editor/index.tsx
- client/src/components/VideoEdit/index.tsx
- yarn.lock
- 하이라이트 추가댐 짱짱!
- 좌표 기반이라 에디터 사이즈가 바뀌면 안 됨 ㅠ_ㅠ
> feat(client): 커서 하이라이트를 레코드할 때 기록하도록 함

- client/src/components/Editor/index.tsx
- client/src/components/VideoEdit/index.tsx
> feat(client): MutationObserver로 효율성을 개선함

- docker-compose-local.yaml
- server/package.json
- server/src/business/AuthService.ts
- server/src/business/UserService.ts
- server/src/controller/UserController.ts
- server/src/database/schema/UserSchema.ts
- server/src/index.ts
- server/src/repository/UserRepository.ts
- server/test/UserAPIScratch.http
- shared/src/entity/InProgressLecture.ts
- shared/src/entity/User.ts
- shared/src/request/LoginInput.ts
- yarn.lock
- 유저 Schema가 변경되었어요.
- 로그인 API를 추가했습니다.
- JWT token을 encoding하고, decoding하는 함수를 추가했어요.
- docker-compose에 `AUTH_KEY`를 추가했어요.
- 유저 Schema에 변경사항이 생겨서 혹시 몰라 프론트 두 분도 리뷰를 걸게요.
> feat(server): 로그인 API 추가

- server/src/business/LectureService.ts
- server/src/controller/LectureController.ts
- server/src/database/Firebase.ts
- server/src/database/schema/LectureSchema.ts
- server/src/database/schema/LessonSchema.ts
- server/src/repository/LectureRepository.ts
- server/test/LectureAPIScratch.http
- shared/src/entity/Lesson.ts
- shared/src/response/CreateLessonResponse.ts
> feat(backend): 차시 추가 API 추가

- client/pages/add-video.tsx
- client/src/components/Editor/index.tsx
- client/src/components/VideoEdit/index.tsx
- 변경 사항을 입력하세요.
- **없다면 해당 섹션을 지우세요**
- 추가 사항을 입력하세요. (없으면 지우세요!)
> feat(client): 슬라이드 여러 장을 수정할 수 있도록 state 수정

- client/pages/index.tsx
- client/pages/lecture/my.tsx
- client/src/assets/add.svg
- client/src/components/Lecture/LectureCardList/LectureCardList.tsx
- client/src/components/Lecture/LectureCardList/styles.ts
- client/src/components/common/Tag/Tag.tsx
- client/src/components/common/TitleSection/index.tsx
- client/src/components/common/TitleSection/styles.ts
- shared/src/entity/Lecture.ts
- 강의 목록 뷰를 추가했어요. (`/lecture/my`)
- API 연동을 하지 않았기 때문에 더미 데이터가 들어가있어요.
> feat(client): 강의 목록 뷰 추가

- server/package.json
- server/src/business/ImageService.ts
- server/src/business/LectureService.ts
- server/src/controller/ImageController.ts
- server/src/database/Firebase.ts
- server/src/index.ts
- server/test/ImageAPIScratch.http
- shared/src/request/FetchUrlInput.ts
- shared/src/response/ImageOutput.ts
- yarn.lock
- Editor.js 에서 사용할 이미지 업로드 API를 추가합니다.
- 프론트와 연동필요
- `fetchUrl` 조금 이상한데?, 파일 시스템에 직접 저장하는거 맘에 들지 않음..
> feat(server): image 업로더를 추가합니다.

- server/package.json
- server/src/business/LectureService.ts
- server/src/business/UserService.ts
- server/src/controller/LectureController.ts
- server/src/database/schema/LectureSchema.ts
- server/src/database/schema/UserSchema.ts
- server/src/repository/LectureRepository.ts
- shared/src/entity/User.ts
- yarn.lock
- Lecture, User의 스키마가 변경됨에 따라 post api도 수정했어요
- 이제 get 해야댐.. 진짜루,,
> fix(server): 추가 API 변경

- server/src/business/UserService.ts
- server/src/database/schema/UserSchema.ts
- shared/src/entity/User.ts
> fix(server): User의 description을 nullable하게 변경

- server/src/business/LectureService.ts
- server/src/business/UserService.ts
- server/src/controller/LectureController.ts
- server/src/repository/LectureRepository.ts
- server/test/LectureAPIScratch.http
- shared/src/response/LectureListOutput.ts
- shared/src/response/LectureOutput.ts
- shared/src/response/UserOutput.ts
> feat(server): 강의 목록 내려주는 API 추가

- server/src/business/LectureService.ts
- server/src/controller/LectureController.ts
- shared/src/response/LectureOutput.ts
> feat(server): LectureOutput에 차시 개수와 수강 여부 추가

- server/src/business/LectureService.ts
- server/src/controller/LectureController.ts
- shared/src/response/LectureDetailOutput.ts
- shared/src/response/LessonListOutput.ts
> fix(server): 차시 정보를 제공하던 API에 강의 정보도 같이 제공

- client/src/components/Editor/index.tsx
- client/src/components/VideoEdit/Slide/index.tsx
- client/src/components/VideoEdit/VideoRecordingController/index.tsx
- client/src/components/VideoEdit/index.tsx
- client/src/components/VideoEdit/states.ts
> feat(client): 영상 녹화를 슬라이드 전체에 함, Preview Mode 추가

- server/src/business/LectureService.ts
- server/src/controller/LectureController.ts
- shared/src/response/LectureDetailOutput.ts
> feat(server): 강의 세부 정보에, 내가 업로드 한 강의인지 필드 추가

- client/pages/add-video.tsx
- client/src/components/VideoEdit/index.tsx
- client/src/components/VideoEdit/styles.ts
- client/src/components/editor-page/EditorToolBar/index.tsx
- client/src/components/editor-page/index.tsx
- 변경 사항을 입력하세요.
- **없다면 해당 섹션을 지우세요**
- 추가 사항을 입력하세요. (없으면 지우세요!)
> feat(client): recoil 상단으로 옮김

- README.md
- shared/src/entity/Lecture.ts
- README 파일을 변경합니다.
- `Lecture` Schema의 `UploadedByMe` 필드를 nullable하게 변경합니다. (강의 생성에 오류가 생김)
> fix(chore): README 변경
